name: CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requiremnets.txt

    - name: Run tests
      run: pytest  # Assuming you have tests written with pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy if changes are pushed to main branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add steps to deploy your application, for instance to a server or cloud provider.

